version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./logs:/home/app/logs
      - ./session.json:/home/app/session.json
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # Only accessible locally
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s
