version: '3.8'

services:
  service:
    build: .
    image: quotes-bot-service
    container_name: quotes-bot-service
    volumes:
      - ./logs:/home/app/logs
      - ./session.json:/home/app/session.json
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:4950:8000"  # Map container's 8000 to host's 4950
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4950/health"]  # Use mapped port
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s
